version: '2'

services:
  exporter_proxy:
    build: ../
    ports:
      - "9099:9099"
    links:
      - node_exporter
      - cadvisor
    volumes:
      - ./config/:/etc/exporter_proxy/:ro
    command: -config /etc/exporter_proxy/config.yml
    entrypoint: go-wrapper run
  node_exporter:
    image: prom/node-exporter
  cadvisor:
    image: google/cadvisor
