listen: "0.0.0.0:9099"

access_log:
  path: "/dev/stdout"
  format: "ltsv"
  fields: ['time', 'time_nsec', 'status', 'size', 'reqtime_nsec', 'backend', 'path', 'query', 'method']

error_log:
  path: "/dev/stderr"

exporters:
  node_exporter:
    url: "http://node_exporter:9100/metrics"
    path: "/node_exporter/metrics"
  cadvisor:
    url: "http://cadvisor:8080/metrics"
    path: "/cadvisor/metrics"
